-- users password = 12345 encripted
INSERT INTO DB_USER (NAME, PASSWORD) VALUES ( 'MICHAEL', '$2a$10$oq.hdX/79OnTN92.jXTgh.ilvSTkW4Sd3ClDnYzSlHCXhWb2a1FSi' );
INSERT INTO DB_USER (NAME, PASSWORD) VALUES ( 'JOANA', '$2a$10$oq.hdX/79OnTN92.jXTgh.ilvSTkW4Sd3ClDnYzSlHCXhWb2a1FSi' );
INSERT INTO DB_ROLE (DS_ROLE) VALUES ( 'ADMIN');
INSERT INTO DB_ROLE (DS_ROLE) VALUES ( 'USER');
INSERT INTO USERS_ROLES (ID_USER, ID_ROLE) VALUES ( 1, 1 );
INSERT INTO USERS_ROLES (ID_USER, ID_ROLE) VALUES ( 1, 2 );
INSERT INTO USERS_ROLES (ID_USER, ID_ROLE) VALUES ( 2, 2 );